name: CI/CD - Password Hashing Tests
# Path: .github/workflows/password-hashing.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-password-hashing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install jest bcryptjs @babel/core @babel/preset-env babel-jest

      - name: Create Jest config
        run: |
          echo "module.exports = { transform: { '^.+\\.js$': 'babel-jest' }, moduleFileExtensions: ['js'] };" > jest.config.js

      - name: Create Babel config
        run: |
          echo "module.exports = { presets: [['@babel/preset-env', { targets: { node: 'current' } }]] };" > babel.config.js

      - name: Create test scripts in package.json if needed
        run: |
          if [ -f package.json ]; then
            node -e "
              const fs = require('fs');
              const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
              pkg.scripts = pkg.scripts || {};
              pkg.scripts.test = 'jest --json --outputFile=test-results.json';
              fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
            "
          else
            echo '{
              "name": "chathaven",
              "version": "1.0.0",
              "description": "ChatHaven application",
              "scripts": {
                "test": "jest --json --outputFile=test-results.json"
              }
            }' > package.json
          fi

      - name: Run Jest Tests
        run: |
          cd tests
          npm test

      - name: Show Test Results
        run: |
          if [ -f test-results.json ]; then
            echo "Test Results Summary:"
            node -e "
              const fs = require('fs');
              const results = JSON.parse(fs.readFileSync('./test-results.json', 'utf8'));
              console.log('Total tests: ' + results.numTotalTests);
              console.log('Passed tests: ' + (results.numTotalTests - results.numFailedTests));
              console.log('Failed tests: ' + results.numFailedTests);
            "
          else
            echo "No test results file found."
          fi

      - name: Notify on Success
        if: success()
        run: echo "✅ Password hashing tests passed!"

      - name: Notify on Failure
        if: failure()
        run: echo "🚨 Tests failed! Fix hashUtils.js errors."
